- name: CLA Assistant
  uses: contributor-assistant/github-action@v2.3.0
  with:
    path-to-signatures: signatures/version1/cla.json
    # Updated path without spaces/special characters
    path-to-document: docs/SupportDocs/TnCs.md
    branch: master
    allowlist: Pray4Lovee, semuelle, takahser, Noc2, PieWol, keeganquigley, laboon, github-actions[bot]
    remote-organization-name: Pray4Lovee
    remote-repository-name: grants-cla
    custom-notsigned-prcomment: >
      Thank you for your submission! Please sign our [CLA](docs/SupportDocs/TnCs.md) by posting 
      "I have read and hereby sign the Contributor License Agreement." as a separate comment.
    custom-pr-sign-comment: I have read and hereby sign the Contributor License Agreement.
    lock-pullrequest-aftermerge: false
    use-dco-flag: false
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
